### ISSUE TITLE
The date of release

### ISSUE THREAD

**Issue by derrick-xwp** [liuyuan-pal/NeuRay#1]
Dear authors,

when will the code be released?

Thanks

**Comment by liuyuan-pal** [comment]
Hi, thanks for your interest in our paper.
Since the paper is a preprint version and we are still working on the paper, we may still make some modifications so we are not going to make the code public immediately. We will release the codes once the paper is going to be formally published.
Thanks again for your understanding!

**Comment by cduguet** [comment]
Great results! Are you planning to publish (and subsequently release the code) for which conference?

**Comment by liuyuan-pal** [comment]
Thanks for your interest!
NeuRay was accepted to CVPR2022 so we'll update the paper and release the codes before 28th March.

**Comment by cduguet** [comment]
Awesome! Looking forward!

**Comment by liuyuan-pal** [comment]
hi all, codes for rendering with the pretrained generalization models are released. I'm still working on cleaning the other codes for release. Thanks for your waiting.

**Comment by liuyuan-pal** [comment]
Generalization training and finetuning codes are released~
