### ISSUE TITLE
A question about "depth_range"

### ISSUE THREAD

**Issue by ZYY-666** [liuyuan-pal/NeuRay#6]
Hello, I noticed that in your database.py, DTUTrainDatabase's "depth_range" is written with a fixed value, while GoogleScannedObjectDatabase's "depth_range" is calculated based on pose. What's the difference between these two ways? And if I want to run your code on ShapeNet dataset, which way do you recommend to get depth_range?

DTUTrain：
![image](https://user-images.githubusercontent.com/69071467/166420722-aafb770f-0a5e-4693-912a-c2b07bf7a65e.png)
GoogleScannedObject：
![image](https://user-images.githubusercontent.com/69071467/166420785-bfc4de22-20e5-42f7-9a29-16d95b7d8b16.png)

**Comment by liuyuan-pal** [comment]
Hi! The depth range denotes the range to include the scene. 
For the DTU train dataset, the fixed depth range is used because we know such a depth range will include the whole object.

If you want to use ShapeNet, you may
1) Project the vertices into every view and compute the depth range similar to
https://github.com/liuyuan-pal/NeuRay/blob/93586a07c863a58c74acfd8aebc226fc88d7af20/dataset/database.py#L519
In the ExampleDatabase, we project the sparse points from the SfM to calculate the depth range. We use `np.percentile` to exclude some possible outlier points and multiply 1.2 to enlarge the range to ensure the range will include the object. In your case, you may replace the points from the SfM with the points of vertices.
2) If you know the object is normalized in the unit sphere (ShapeNet models are normalized), and you know the distance from the camera to the origin, you may also manually specify the depth range according to your setting.

In my experience, using a more compact depth range leads to better performance because the searching range is smaller for the rendering to find the surface. So, option 1 is usually better than 2.

**Comment by ZYY-666** [comment]
Thank you very much for your detailed and quick reply！ I will try your suggestions.

**Comment by ZYY-666** [comment]
Thank you very much for your detailed and quick reply！ I will try your suggestions.
